### ISSUE TITLE
Rail package for GNU Guix

### ISSUE THREAD

**Issue by abcdw** [Sasanidas/Rail#4]
Hi, Fermin!

I've packaged rail in Guix, it doesn't run tests during build yet, but I think it's ok for now.
  
https://git.savannah.gnu.org/cgit/guix.git/commit/?id=0433e7f3c200936fbf77f22aa3b433413d17d0fa

Also, I'm working on [guile-nrepl](https://git.sr.ht/~abcdw/guile-nrepl), so maybe later we can implement integration tests for rail+guile-nrepl.  It will make it possible to have a relatively slim and easy to setup testing environment and enable tests for [emacs-rail](https://git.savannah.gnu.org/cgit/guix.git/commit/?id=0433e7f3c200936fbf77f22aa3b433413d17d0fa
) package.

Thank you for your work, keep rocking! :)

**Comment by Sasanidas** [comment]
Hey!

> I've packaged rail in Guix, it doesn't run tests during build yet, but I think it's ok for now.
> 
> https://git.savannah.gnu.org/cgit/guix.git/commit/?id=0433e7f3c200936fbf77f22aa3b433413d17d0fa

Thanks a lot! I started using Guix for my secondary computer some months ago, but I don't use it for managing GNU Emacs dependencies (I also realise that someone has put my islisp-mode package there).

> Also, I'm working on [guile-nrepl](https://git.sr.ht/~abcdw/guile-nrepl), so maybe later we can implement integration tests for rail+guile-nrepl. It will make it possible to have a relatively slim and easy to setup testing environment and enable tests for [emacs-rail](https://git.savannah.gnu.org/cgit/guix.git/commit/?id=0433e7f3c200936fbf77f22aa3b433413d17d0fa) package.

Sounds awesome, we can indeed add some tests, it should be quite easy to do, I'm planning to write another nrepl client for Elixir soon™ so if we can ensure that works with all of these implementation, Rail maybe the first non-clojure nrepl client :smile:  .

I'll try it out these week and let you know how it goes :+1:

**Comment by abcdw** [comment]
On 2023-06-13 01:56, Sasanidas wrote:

> Sounds awesome, we can indeed add some tests, it should be quite easy
> to do, I'm planning to write another nrepl client for Elixir soon™ so
> if we can ensure that works with all of these implementation, Rail
> maybe the first non-clojure nrepl client :smile: .
>
> I'll try it out these week and let you know how it goes :+1: 

I'm not sure if it ready yet, I didn't expect so prompt response :D Only
implemented bencoding and a simple tcp server with a drafty eval op,
however maybe something will change before you get to it :)

Also, I plan to try rail with guile-nrepl soon (that's one of the
reasons I packaged it for guix), so maybe I'll get all the basics
covered quickly.

> Thanks a lot! I started using Guix for my secondary computer some
> months ago, but I don't use it for managing GNU Emacs dependencies (I
> also realise that someone has put my islisp-mode package there).
>

BTW, we do a quite nice emacs distribution on top of guix, actually it's
a full-blown operating system distribution, but emacs is important part
of it (which can be used separately, without the rest).

-- 
Best regards,
Andrew Tropin

**Comment by Sasanidas** [comment]
> Also, I plan to try rail with guile-nrepl soon (that's one of the
> reasons I packaged it for guix), so maybe I'll get all the basics
> covered quickly.

Sounds great, I would read the code so I remember some scheme (too much Common Lisp parenthesis), if you find some problem with Rail, don't hesitate to open an issue or pull request.

> BTW, we do a quite nice emacs distribution on top of guix, actually it's
> a full-blown operating system distribution, but emacs is important part
> of it (which can be used separately, without the rest).

Oh I see, do you have a link where I can maybe find more information?

Thanks!

**Comment by abcdw** [comment]
On 2023-06-13 10:54, Fermin MF wrote:

>> Also, I plan to try rail with guile-nrepl soon (that's one of the
>> reasons I packaged it for guix), so maybe I'll get all the basics
>> covered quickly.
>
> Sounds great, I would read the code so I remember some scheme (too
> much Common Lisp parenthesis), if you find some problem with Rail,
> don't hesitate to open an issue or pull request.

Sure!

>> BTW, we do a quite nice emacs distribution on top of guix, actually it's
>> a full-blown operating system distribution, but emacs is important part
>> of it (which can be used separately, without the rest).
>
> Oh I see, do you have a link where I can maybe find more information?

A good starting point will be https://trop.in/rde/, but let me know if
you have any questions or join our IRC/matrix room
https://matrix.to/#/#tropin:libera.chat.

-- 
Best regards,
Andrew Tropin

**Comment by Sasanidas** [comment]
Ohh I see, so it's like a Guix package manager library + custom configuration, seems really cool :+1:

**Comment by abcdw** [comment]
On 2023-06-14 10:14, Fermin MF wrote:

> Ohh I see, so it's like a Guix package manager library + custom
> configuration, seems really cool :+1:

Yep, you are right.  It's API on top of Guix + predefined customizable
configs/battaries.

-- 
Best regards,
Andrew Tropin

**Comment by abcdw** [comment]
It's not necessary, but if you could add info about https://packages.guix.gnu.org/packages/emacs-rail/0.4.0/ to Installation section, it would be cool! 

Closing the issue.
